=== navaneethbv/Web-Programming-Languages/Books/WebContent/Books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- String type where first letter is capital -->
	<xs:simpleType name="StringFirstCapital">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z].*" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author middle name -->
	<xs:simpleType name="MiddleInitial">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][.]" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author name -->
	<xs:complexType name="Name">
		<xs:sequence>
			<xs:element name="lastname" type="StringFirstCapital" />
			<xs:element name="middlename" type="MiddleInitial"
				minOccurs="0" />
			<xs:element name="firstname" type="StringFirstCapital" />
		</xs:sequence>
	</xs:complexType>

	<!-- Author date of birth -->
	<xs:simpleType name="DateOfBirth">
		<xs:restriction base="xs:date">
			<xs:minInclusive value="1900-01-01" />
			<xs:maxInclusive value="2015-12-31" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author highest education -->
	<xs:simpleType name="HighestEducation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BA" />
			<xs:enumeration value="BS" />
			<xs:enumeration value="MS" />
			<xs:enumeration value="MBA" />
			<xs:enumeration value="PHD" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author address street name -->
	<xs:simpleType name="StreetName">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+[\s][A-Za-z\s]+" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author address apartment number -->
	<xs:simpleType name="AptNumber">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="100" />
			<xs:maxExclusive value="2000" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author address zip code -->
	<xs:simpleType name="ZipCode">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="11111" />
			<xs:maxInclusive value="99999" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author address country -->
	<xs:simpleType name="Country">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]*" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Author address type -->
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="street_name" type="StreetName" />
			<xs:element name="Apt" type="AptNumber" minOccurs="0" />
			<xs:element name="city" type="StringFirstCapital" />
			<xs:element name="zipcode" type="ZipCode" />
			<xs:element name="country" type="Country" />
		</xs:sequence>
	</xs:complexType>

	<!-- Author type -->
	<xs:complexType name="Author">
		<xs:sequence>
			<xs:element name="name" type="Name" />
			<xs:element name="bday" type="DateOfBirth" />
			<xs:element name="education" type="HighestEducation" />
			<xs:element name="address" type="Address" />
		</xs:sequence>
	</xs:complexType>

	<!-- Publisher name -->
	<xs:simpleType name="PublisherName">
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z][A-Za-z]*[\s]?)+" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Publisher address type -->
	<xs:complexType name="PublisherAddress">
		<xs:sequence>
			<xs:element name="street_name" type="StreetName" />
			<xs:element name="Suite" type="xs:integer" minOccurs="0" />
			<xs:element name="city" type="StringFirstCapital" />
			<xs:element name="zipcode" type="ZipCode" />
			<xs:element name="country" type="Country" />
		</xs:sequence>
	</xs:complexType>

	<!-- Publisher type -->
	<xs:complexType name="Publisher">
		<xs:sequence>
			<xs:element name="name" type="PublisherName" />
			<xs:element name="address" type="PublisherAddress" />
		</xs:sequence>
	</xs:complexType>

	<!-- ISBN type -->
	<xs:simpleType name="ISBN">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9]{3}[-][A-Za-z0-9]{3}[-][A-Za-z0-9]{4}" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Currency type -->
	<xs:simpleType name="Price">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Duration type -->
	<xs:simpleType name="TotalTime">
		<xs:restriction base="xs:duration">
			<xs:pattern value="[^T]+" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Book type -->
	<xs:complexType name="Book">
		<xs:sequence>
			<xs:element name="title" type="StringFirstCapital" />
			<xs:element name="isbn" type="ISBN" />
			<xs:element name="price" type="Price" />
			<xs:element name="publicationdate" type="xs:date" />
			<xs:element name="time" type="TotalTime" />
			<xs:element name="author" type="Author" maxOccurs="unbounded" />
			<xs:element name="publisher" type="Publisher" />
		</xs:sequence>
	</xs:complexType>

	<!-- Books holder for book type -->
	<xs:element name="Books">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="book" type="Book" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== navaneethbv/Web-Programming-Languages/Books/WebContent/Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Books.xsd">
	<book>
		<title>Machine Learning</title>
		<isbn>007-042-8077</isbn>
		<price>79.99</price>
		<publicationdate>1997-03-01</publicationdate>
		<time>P18Y1M1D</time>
		<author>
			<name>
				<lastname>Mitchell</lastname>
				<middlename>M.</middlename>
				<firstname>Tom</firstname>
			</name>
			<bday>1985-01-01</bday>
			<education>PHD</education>
			<address>
				<street_name>1 CMU</street_name>
				<Apt>123</Apt>
				<city>Pittsburgh</city>
				<zipcode>15201</zipcode>
				<country>USA</country>
			</address>
		</author>
		<publisher>
			<name>McGraw Hill</name>
			<address>
				<street_name>19 Terry Ave</street_name>
				<city>Redmond</city>
				<zipcode>98052</zipcode>
				<country>USA</country>
			</address>
		</publisher>
	</book>

	<book>
		<title>Fundamentals of database systems</title>
		<isbn>013-608-6209</isbn>
		<price>89.99</price>
		<publicationdate>2011-03-01</publicationdate>
		<time>P4Y1M1D</time>
		<author>
			<name>
				<lastname>Elmasri</lastname>
				<firstname>Navathe</firstname>
			</name>
			<bday>1987-02-15</bday>
			<education>PHD</education>
			<address>
				<street_name>701 South Nedderman Drive</street_name>
				<city>Arlington</city>
				<zipcode>76019</zipcode>
				<country>USA</country>
			</address>
		</author>
		<author>
			<name>
				<lastname>Shamkant</lastname>
				<firstname>Navathe</firstname>
			</name>
			<bday>1975-08-05</bday>
			<education>PHD</education>
			<address>
				<street_name>801 Atlantic Dr</street_name>
				<Apt>320</Apt>
				<city>Atlanta</city>
				<zipcode>30332</zipcode>
				<country>USA</country>
			</address>
		</author>
		<publisher>
			<name>Pearson Education Inc</name>
			<address>
				<street_name>501 Bolyson</street_name>
				<Suite>900</Suite>
				<city>Boston</city>
				<zipcode>21160</zipcode>
				<country>USA</country>
			</address>
		</publisher>
	</book>

	<book>
		<title>Hadoop</title>
		<isbn>128-317-9414</isbn>
		<price>109.99</price>
		<publicationdate>2010-10-01</publicationdate>
		<time>P4Y6M1D</time>
		<author>
			<name>
				<lastname>White</lastname>
				<firstname>Tom</firstname>
			</name>
			<bday>1982-05-11</bday>
			<education>PHD</education>
			<address>
				<street_name>1 UC</street_name>
				<Apt>1986</Apt>
				<city>Cambridge</city>
				<zipcode>12315</zipcode>
				<country>USA</country>
			</address>
		</author>
		<publisher>
			<name>O Reilly Media</name>
			<address>
				<street_name>1003 Gravenstein</street_name>
				<Suite>1</Suite>
				<city>Sebassopol</city>
				<zipcode>93472</zipcode>
				<country>USA</country>
			</address>
		</publisher>
	</book>

	<book>
		<title>Introduction to Algorithms, Third Edition</title>
		<isbn>128-317-9414</isbn>
		<price>104.99</price>
		<publicationdate>2012-03-19</publicationdate>
		<time>P2Y5M11D</time>
		<author>
			<name>
				<lastname>Cormen</lastname>
				<middlename>H.</middlename>
				<firstname>Thomas</firstname>
			</name>
			<bday>1979-08-21</bday>
			<education>MBA</education>
			<address>
				<street_name>6211 Sudikoff Laboratory</street_name>
				<city>Hanover</city>
				<zipcode>37550</zipcode>
				<country>USA</country>
			</address>
		</author>
		<author>
			<name>
				<lastname>Leiserson</lastname>
				<middlename>E.</middlename>
				<firstname>Charles</firstname>
			</name>
			<bday>1953-11-10</bday>
			<education>MS</education>
			<address>
				<street_name>32 Vassar Street</street_name>
				<city>Cambridge</city>
				<zipcode>21390</zipcode>
				<country>USA</country>
			</address>
		</author>
		<publisher>
			<name>The MIT Press</name>
			<address>
				<street_name>1 Duchess Street</street_name>
				<city>London</city>
				<zipcode>34567</zipcode>
				<country>UK</country>
			</address>
		</publisher>
	</book>

	<book>
		<title>Introduction to Algorithms, Second Edition</title>
		<isbn>128-317-9414</isbn>
		<price>95.00</price>
		<publicationdate>2008-10-21</publicationdate>
		<time>P2Y5M11D</time>
		<author>
			<name>
				<lastname>Cormen</lastname>
				<middlename>H.</middlename>
				<firstname>Thomas</firstname>
			</name>
			<bday>1979-08-21</bday>
			<education>MBA</education>
			<address>
				<street_name>6211 Sudikoff Laboratory</street_name>
				<city>Hanover</city>
				<zipcode>37550</zipcode>
				<country>USA</country>
			</address>
		</author>
		<author>
			<name>
				<lastname>Leiserson</lastname>
				<middlename>E.</middlename>
				<firstname>Charles</firstname>
			</name>
			<bday>1953-11-10</bday>
			<education>MS</education>
			<address>
				<street_name>32 Vassar Street</street_name>
				<city>Cambridge</city>
				<zipcode>21390</zipcode>
				<country>USA</country>
			</address>
		</author>
		<publisher>
			<name>The MIT Press</name>
			<address>
				<street_name>1 Duchess Street</street_name>
				<city>London</city>
				<zipcode>34567</zipcode>
				<country>UK</country>
			</address>
		</publisher>
	</book>
</Books>
